from PyQt5 import QtCore, QtGui, QtWidgets
from Classes.CodeTextWidget import Editor

class QtGecko_GUI(object):
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        self.MainWindow.setObjectName("MainWindow")
        self.MainWindow.resize(1204, 646)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1201, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.Codes_Tab = QtWidgets.QWidget()
        self.Codes_Tab.setObjectName("Codes_Tab")
        self.CodeList_Label = QtWidgets.QLabel(self.Codes_Tab)
        self.CodeList_Label.setEnabled(True)
        self.CodeList_Label.setGeometry(QtCore.QRect(4, 10, 81, 17))
        self.CodeList_Label.setObjectName("CodeList_Label")
        self.SelectedCode_Label = QtWidgets.QLabel(self.Codes_Tab)
        self.SelectedCode_Label.setGeometry(QtCore.QRect(403, 10, 111, 17))
        self.SelectedCode_Label.setObjectName("SelectedCode_Label")
        self.SelectedCodeComment_Label = QtWidgets.QLabel(self.Codes_Tab)
        self.SelectedCodeComment_Label.setGeometry(QtCore.QRect(801, 10, 171, 17))
        self.SelectedCodeComment_Label.setObjectName("SelectedCodeComment_Label")
        self.Checkbox_ScrollArea = QtWidgets.QScrollArea(self.Codes_Tab)
        self.Checkbox_ScrollArea.setWidgetResizable(True)
        self.Checkbox_ScrollArea.verticalScrollBar().setStyleSheet("background-color: lightGray;")
        self.Checkbox_ScrollArea.horizontalScrollBar().setStyleSheet("background-color: lightGray;")
        self.Checkbox_ScrollArea.setGeometry(QtCore.QRect(4, 30, 391, 291))
        self.Checkbox_ScrollArea.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Checkbox_ScrollArea.setWidgetResizable(True)
        self.Checkbox_ScrollArea.setObjectName("Checkbox_ScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 389, 289))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.Checkbox_ScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.SelectedCode_Text = Editor(self.Codes_Tab)
        self.SelectedCode_Text.setReadOnly(True)
        self.SelectedCode_Text.setGeometry(QtCore.QRect(403, 30, 391, 291))
        self.SelectedCode_Text.setObjectName("SelectedCode_Text")
        self.SelectedCodeComment_Text = QtWidgets.QTextEdit(self.Codes_Tab)
        self.SelectedCodeComment_Text.setGeometry(QtCore.QRect(801, 30, 391, 291))
        self.SelectedCodeComment_Text.setReadOnly(True)
        self.SelectedCodeComment_Text.setObjectName("SelectedCodeComment_Text")
        self.AddCode_Button = QtWidgets.QPushButton(self.Codes_Tab)
        self.AddCode_Button.setGeometry(QtCore.QRect(4, 400, 290, 25))
        self.AddCode_Button.setObjectName("AddCode_Button")
        self.SaveCodeList_Button = QtWidgets.QPushButton(self.Codes_Tab)
        self.SaveCodeList_Button.setEnabled(False)
        self.SaveCodeList_Button.setGeometry(QtCore.QRect(300, 400, 290, 25))
        self.SaveCodeList_Button.setObjectName("SaveCodeList_Button")
        self.UntickAll_Button = QtWidgets.QPushButton(self.Codes_Tab)
        self.UntickAll_Button.setGeometry(QtCore.QRect(600, 400, 290, 25))
        self.UntickAll_Button.setObjectName("UntickAll_Button")
        self.ExportCodeList_Button = QtWidgets.QPushButton(self.Codes_Tab)
        self.ExportCodeList_Button.setGeometry(QtCore.QRect(900, 400, 290, 25))
        self.ExportCodeList_Button.setObjectName("ExportCodeList_Button")
        self.DisableCodes_Button = QtWidgets.QPushButton(self.Codes_Tab)
        self.DisableCodes_Button.setEnabled(False)
        self.DisableCodes_Button.setGeometry(QtCore.QRect(300, 430, 290, 25))
        self.DisableCodes_Button.setObjectName("DisableCodes_Button")
        self.SendCodes_Button = QtWidgets.QPushButton(self.Codes_Tab)
        self.SendCodes_Button.setEnabled(False)
        self.SendCodes_Button.setGeometry(QtCore.QRect(4, 430, 290, 25))
        self.SendCodes_Button.setObjectName("SendCodes_Button")
        self.CodeTypesDoc_Button = QtWidgets.QPushButton(self.Codes_Tab)
        self.CodeTypesDoc_Button.setGeometry(QtCore.QRect(900, 430, 290, 25))
        self.CodeTypesDoc_Button.setObjectName("CodeTypesDoc_Button")
        self.LoadCodeList_Button = QtWidgets.QPushButton(self.Codes_Tab)
        self.LoadCodeList_Button.setGeometry(QtCore.QRect(600, 430, 290, 25))
        self.LoadCodeList_Button.setObjectName("LoadCodeList_Button")
        self.ImportGCTU_Button = QtWidgets.QPushButton(self.Codes_Tab)
        self.ImportGCTU_Button.setGeometry(QtCore.QRect(600, 460, 290, 25))
        self.ImportGCTU_Button.setObjectName("ImportGCTU_Button")
        self.ExportGCTU_Button = QtWidgets.QPushButton(self.Codes_Tab)
        self.ExportGCTU_Button.setEnabled(True)
        self.ExportGCTU_Button.setGeometry(QtCore.QRect(300, 460, 290, 25))
        self.ExportGCTU_Button.setObjectName("ExportGCTU_Button")
        self.CodeTitleSearch_Button = QtWidgets.QPushButton(self.Codes_Tab)
        self.CodeTitleSearch_Button.setEnabled(True)
        self.CodeTitleSearch_Button.setGeometry(QtCore.QRect(4, 460, 290, 25))
        self.CodeTitleSearch_Button.setObjectName("CodeTitleSearch_Button")
        self.DownloadCodes_Button = QtWidgets.QPushButton(self.Codes_Tab)
        self.DownloadCodes_Button.setGeometry(QtCore.QRect(900, 460, 290, 25))
        self.DownloadCodes_Button.setObjectName("DownloadCodes_Button")
        self.ActiveCodes_Label = QtWidgets.QLabel(self.Codes_Tab)
        self.ActiveCodes_Label.setGeometry(QtCore.QRect(4, 327, 281, 17))
        self.ActiveCodes_Label.setObjectName("ActiveCodes_Label")
        self.TotalCodes_Label = QtWidgets.QLabel(self.Codes_Tab)
        self.TotalCodes_Label.setGeometry(QtCore.QRect(4, 350, 281, 17))
        self.TotalCodes_Label.setObjectName("TotalCodes_Label")
        self.ActiveCodeLines_Label = QtWidgets.QLabel(self.Codes_Tab)
        self.ActiveCodeLines_Label.setGeometry(QtCore.QRect(4, 372, 281, 17))
        self.ActiveCodeLines_Label.setObjectName("ActiveCodeLines_Label")

        self.WhichCode_Label = QtWidgets.QLabel(self.Codes_Tab)
        self.WhichCode_Label.setGeometry(QtCore.QRect(184, 323, 300, 25))
        self.WhichCode_Label.setObjectName("WhichCode")

        self.Author_Label = QtWidgets.QLabel(self.Codes_Tab)
        self.Author_Label.setGeometry(QtCore.QRect(184, 346, 300, 25))
        self.Author_Label.setObjectName("Author_Label")

        self.ARW_Label = QtWidgets.QLabel(self.Codes_Tab)
        self.ARW_Label.setGeometry(QtCore.QRect(184, 368, 300, 25))
        self.ARW_Label.setObjectName("ARW_Label")

        self.tabWidget.addTab(self.Codes_Tab, "")
        self.Miscellaneous_Tab = QtWidgets.QWidget()
        self.Miscellaneous_Tab.setObjectName("Miscellaneous_Tab")
        self.WiiUFirmware_Button = QtWidgets.QPushButton(self.Miscellaneous_Tab)
        self.WiiUFirmware_Button.setEnabled(False)
        self.WiiUFirmware_Button.setGeometry(QtCore.QRect(5, 5, 591, 25))
        self.WiiUFirmware_Button.setObjectName("WiiUFirmware_Button")
        self.LocalIP_Button = QtWidgets.QPushButton(self.Miscellaneous_Tab)
        self.LocalIP_Button.setGeometry(QtCore.QRect(5, 38, 591, 25))
        self.LocalIP_Button.setObjectName("LocalIP_Button")
        self.GeckoServerVersion_Button = QtWidgets.QPushButton(self.Miscellaneous_Tab)
        self.GeckoServerVersion_Button.setEnabled(False)
        self.GeckoServerVersion_Button.setGeometry(QtCore.QRect(5, 70, 591, 25))
        self.GeckoServerVersion_Button.setObjectName("GeckoServerVersion_Button")
        self.BuildDate_Button = QtWidgets.QPushButton(self.Miscellaneous_Tab)
        self.BuildDate_Button.setGeometry(QtCore.QRect(5, 135, 591, 25))
        self.BuildDate_Button.setObjectName("BuildDate_Button")
        self.BugTracker_Button = QtWidgets.QPushButton(self.Miscellaneous_Tab)
        self.BugTracker_Button.setGeometry(QtCore.QRect(5, 167, 591, 25))
        self.BugTracker_Button.setObjectName("BugTracker_Button")
        self.DataTypeConversion_Button = QtWidgets.QPushButton(self.Miscellaneous_Tab)
        self.DataTypeConversion_Button.setGeometry(QtCore.QRect(600, 167, 591, 25))
        self.DataTypeConversion_Button.setObjectName("DataTypeConversion_Button")
        self.ConnectionTimeout_Checkbox = QtWidgets.QCheckBox(self.Miscellaneous_Tab)
        self.ConnectionTimeout_Checkbox.setGeometry(QtCore.QRect(8, 234, 171, 23))
        self.ConnectionTimeout_Checkbox.setObjectName("ConnectionTimeout_Checkbox")
        self.SetTheme_Label = QtWidgets.QLabel(self.Miscellaneous_Tab)
        self.SetTheme_Label.setGeometry(QtCore.QRect(8, 264, 80, 23))
        self.SetTheme_Label.setObjectName("SetTheme_Label")
        self.SetTheme_ComboBox = QtWidgets.QComboBox(self.Miscellaneous_Tab)
        self.SetTheme_ComboBox.setGeometry(QtCore.QRect(90, 264, 171, 23))
        self.SetTheme_ComboBox.setObjectName("SetTheme_ComboBox")
        self.tabWidget.addTab(self.Miscellaneous_Tab, "")
        self.ExternalTools_Tab = QtWidgets.QWidget()
        self.ExternalTools_Tab.setObjectName("ExternalTools_Tab")
        self.TCPGecko_Label = QtWidgets.QLabel(self.ExternalTools_Tab)
        self.TCPGecko_Label.setGeometry(QtCore.QRect(60, 12, 1081, 31))
        self.TCPGecko_Label.setStyleSheet("color: #bb0d00;")
        self.TCPGecko_Label.setObjectName("TCPGecko_Label")
        self.TCPGeckoInstaller_Button = QtWidgets.QPushButton(self.ExternalTools_Tab)
        self.TCPGeckoInstaller_Button.setGeometry(QtCore.QRect(8, 55, 1181, 25))
        self.TCPGeckoInstaller_Button.setObjectName("TCPGeckoInstaller_Button")
        self.tabWidget.addTab(self.ExternalTools_Tab, "")
        self.About_Tab = QtWidgets.QWidget()
        self.About_Tab.setObjectName("About_Tab")
        self.AboutCredits_TextEdit = QtWidgets.QLabel(self.About_Tab)
        self.AboutCredits_TextEdit.setObjectName("AboutCredits_TextEdit")
        self.AboutCredits_TextEdit.setOpenExternalLinks(True)
        self.tabWidget.addTab(self.About_Tab, "")
        self.IPv4_Label = QtWidgets.QLabel(self.centralwidget)
        self.IPv4_Label.setGeometry(QtCore.QRect(4, 593, 101, 17))
        self.IPv4_Label.setObjectName("IPv4_Label")
        self.Connection_Bar = QtWidgets.QLineEdit(self.centralwidget)
        self.Connection_Bar.setAlignment(QtCore.Qt.AlignCenter)
        self.Connection_Bar.setGeometry(QtCore.QRect(112, 590, 741, 25))
        self.Connection_Bar.setStyleSheet("background-color: red;")
        self.Connection_Bar.setObjectName("Connection_Bar")
        self.Connect_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Connect_Button.setEnabled(True)
        self.Connect_Button.setGeometry(QtCore.QRect(861, 590, 111, 25))
        self.Connect_Button.setObjectName("Connect_Button")
        self.Connect_Button.setEnabled(False)
        self.Disconnect_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Disconnect_Button.setEnabled(False)
        self.Disconnect_Button.setGeometry(QtCore.QRect(981, 590, 111, 25))
        self.Disconnect_Button.setObjectName("Disconnect_Button")
        self.Help_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Help_Button.setGeometry(QtCore.QRect(1101, 590, 91, 25))
        self.Help_Button.setObjectName("Help_Button")
        self.MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi()
        #self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self.MainWindow)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.MainWindow.setWindowTitle(_translate("MainWindow", "QtGecko | KorOwOzin"))
        self.CodeList_Label.setText(_translate("MainWindow", "Code List:"))
        self.SelectedCode_Label.setText(_translate("MainWindow", "Selected Code:"))
        self.SelectedCodeComment_Label.setText(_translate("MainWindow", "Selected Code Comment:"))
        self.AddCode_Button.setText(_translate("MainWindow", "Add Code"))
        self.SaveCodeList_Button.setText(_translate("MainWindow", "Save Code List"))
        self.UntickAll_Button.setText(_translate("MainWindow", "Untick All"))
        self.ExportCodeList_Button.setText(_translate("MainWindow", "Export Code List"))
        self.DisableCodes_Button.setText(_translate("MainWindow", "Disable Codes"))
        self.SendCodes_Button.setText(_translate("MainWindow", "Send Codes"))
        self.CodeTypesDoc_Button.setText(_translate("MainWindow", "Code Types Documentation"))
        self.LoadCodeList_Button.setText(_translate("MainWindow", "Load Code List"))
        self.ImportGCTU_Button.setText(_translate("MainWindow", "Import GCTU"))
        self.ExportGCTU_Button.setText(_translate("MainWindow", "Export GCTU"))
        self.CodeTitleSearch_Button.setText(_translate("MainWindow", "Code Title Search"))
        self.DownloadCodes_Button.setText(_translate("MainWindow", "Download Codes"))
        self.ActiveCodes_Label.setText(_translate("MainWindow", "Active Codes: 0"))
        self.TotalCodes_Label.setText(_translate("MainWindow", "Total Code Count: 0"))
        self.ActiveCodeLines_Label.setText(_translate("MainWindow", "Active Code Lines: 0"))
        self.WhichCode_Label.setText(_translate("MainWindow", "Code Name: null"))
        self.Author_Label.setText(_translate("MainWindow", "Code Author: null"))
        self.ARW_Label.setText(_translate("MainWindow", "Is Assembly RAM Write? : null"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Codes_Tab), _translate("MainWindow", "Codes"))
        self.WiiUFirmware_Button.setText(_translate("MainWindow", "Wii U Firmware Version"))
        self.LocalIP_Button.setText(_translate("MainWindow", "Computer Local IP Address(es)"))
        self.GeckoServerVersion_Button.setText(_translate("MainWindow", "TCPGecko Server Version"))
        self.BuildDate_Button.setText(_translate("MainWindow", "Build Date"))
        self.BugTracker_Button.setText(_translate("MainWindow", "Bug Tracker"))
        self.DataTypeConversion_Button.setText(_translate("MainWindow", "Datatype Conversion"))
        self.ConnectionTimeout_Checkbox.setText(_translate("MainWindow", "Connection Timeouts"))
        self.SetTheme_Label.setText(_translate("MainWindow", "Set Theme:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Miscellaneous_Tab), _translate("MainWindow", "Miscellaneous"))
        self.TCPGecko_Label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Make sure to use the TCP Gecko installer from below to avoid incompatibility problems</span></p></body></html>"))
        self.TCPGeckoInstaller_Button.setText(_translate("MainWindow", "TCP Gecko Installer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ExternalTools_Tab), _translate("MainWindow", "External Tools"))
        self.AboutCredits_TextEdit.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Monospace\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This application is a wireless cheat code manager and development aid for Wii U titles.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" text-decoration: underline;\">Credits</span>:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">BullyWiiPlaza</span> for creating and programming the original <a href=\"https://github.com/Bullywiiplaza/JGeckoU/\"><span style=\" text-decoration: underline; color:#0000ff;\">JGecko U</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Korozin</span> for creating this <a href=\"https://github.com/Korozin/QtGecko/\"><span style=\" text-decoration: underline; color:#0000ff;\">re-creation</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Pop-Apple</span> for creating <a href=\"https://github.com/Pop-Apple/JGeckoU-Reproduction/\"><span style=\" text-decoration: underline; color:#0000ff;\">this</span></a> as my inspiration</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Vincent-Coding</span> for creating <a href=\"https://github.com/vincent-coding/uGecko\"><span style=\" text-decoration: underline; color:#0000ff;\">uGecko</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">NWPlayer123</span> for creating the original python <a href=\"https://github.com/wiiudev/pyGecko\"><span style=\" text-decoration: underline; color:#0000ff;\">TCPGecko</span></a> library</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.About_Tab), _translate("MainWindow", "About"))
        self.IPv4_Label.setText(_translate("MainWindow", "IPv4 Address:"))
        self.Connect_Button.setText(_translate("MainWindow", "Connect"))
        self.Disconnect_Button.setText(_translate("MainWindow", "Disconnect"))
        self.Help_Button.setText(_translate("MainWindow", "Help"))